export const cvProfileFacts = [
  "La Quang Ninh is a final-year Data Science student at VNUHCM - University of Science (HCMUS).",
  "Ninh's focus includes AI Engineering, Data Science, Deep Learning, NLP, and Computer Vision.",
  "Contact email: lwanih.work@gmail.com.",
  "Phone number: 0878 500 607.",
  "Location: Thu Duc, Ho Chi Minh City, Vietnam.",
  "Core programming skills: Python, SQL, and C++.",
  "AI/ML stack: PyTorch, Scikit-learn, Pandas, NumPy, Matplotlib.",
  "Modeling and techniques: YOLOv8, PhoBERT, Matrix Factorization, Neural Collaborative Filtering.",
  "Tools and deployment: FastAPI, Streamlit, Docker, Git, VS Code, Render.",
  "Featured project: Smart Recommendation System (Python, React, TypeScript, Docker).",
  "Featured project: Vietnamese Sentiment Analysis System (PyTorch, Transformers, Streamlit, Selenium).",
  "Featured project: Edge AI Security Monitoring System (YOLOv8, OpenCV, React, TypeScript).",
  "Featured project: Diabetes Health Risk Analysis (Python, Pandas, Scikit-learn, Matplotlib, Seaborn).",
  "Featured project: Game A/B Testing Analysis (A/B testing, statistics, product analytics).",
  "Featured project: Interactive Gift Landing Page (HTML, CSS, JavaScript).",
  "Ninh is available and open to internship opportunities in AI/Data fields.",
];

export const cvProfileFactsVi = [
  "La Quang Ninh là sinh viên năm cuối ngành Khoa học Dữ liệu tại Đại học Khoa học Tự nhiên (HCMUS).",
  "Định hướng chính: AI Engineering, Data Science, Deep Learning, NLP và Computer Vision.",
  "Email liên hệ: lwanih.work@gmail.com.",
  "Số điện thoại: 0878 500 607.",
  "Địa chỉ: Thủ Đức, TP. Hồ Chí Minh.",
  "Kỹ năng lập trình chính: Python, SQL, C++.",
  "Stack AI/ML: PyTorch, Scikit-learn, Pandas, NumPy, Matplotlib.",
  "Kỹ thuật và mô hình: YOLOv8, PhoBERT, Matrix Factorization, Neural Collaborative Filtering.",
  "Công cụ triển khai: FastAPI, Streamlit, Docker, Git, VS Code, Render.",
  "Dự án nổi bật: Smart Recommendation System (Python, React, TypeScript, Docker).",
  "Dự án nổi bật: Vietnamese Sentiment Analysis System (PyTorch, Transformers, Streamlit, Selenium).",
  "Dự án nổi bật: Edge AI Security Monitoring System (YOLOv8, OpenCV, React, TypeScript).",
  "Dự án nổi bật: Diabetes Health Risk Analysis (Python, Pandas, Scikit-learn, Matplotlib, Seaborn).",
  "Dự án nổi bật: Game A/B Testing Analysis (A/B testing, thống kê, product analytics).",
  "Dự án nổi bật: Interactive Gift Landing Page (HTML, CSS, JavaScript).",
  "Ninh sẵn sàng cho cơ hội thực tập trong lĩnh vực AI/Data.",
];
